import { metaTypes } from './metaTypes';

export const vehiclesMeta = {
  id: metaTypes.INTEGER_PK_AI,
  bodyStyle: metaTypes.TEXT,
  cityFuelEfficiency: metaTypes.INTEGER,
  doors: metaTypes.TEXT,
  driveLine: metaTypes.TEXT,
  engine: metaTypes.TEXT,
  engineSize: metaTypes.TEXT,
  exteriorColor: metaTypes.TEXT,
  fuelType: metaTypes.TEXT,
  highwayFuelEfficiency: metaTypes.INTEGER,
  fuelPercentage: metaTypes.REAL,
  interiorColor: metaTypes.TEXT,
  internetPrice: metaTypes.REAL,
  inventoryDate: metaTypes.TEXT,
  inventoryType: metaTypes.TEXT,
  link: metaTypes.TEXT,
  location: metaTypes.TEXT,
  make: metaTypes.TEXT,
  model: metaTypes.TEXT,
  modelYear: metaTypes.INTEGER,
  msrp: metaTypes.REAL,
  newOrUsed: metaTypes.TEXT,
  normalFuelType: metaTypes.TEXT,
  odometer: metaTypes.INTEGER,
  retailValue: metaTypes.REAL,
  status: metaTypes.TEXT,
  stockNumber: metaTypes.TEXT,
  trim: metaTypes.TEXT,
  vin: metaTypes.TEXT,
  year: metaTypes.INTEGER
};
